### PR TITLE
Added myself

### PR DESCRIPTION
**Pull request by mohsin-code**
## Issue

#260
#259 

## Description

Add myself to readme and to contributors.js

## Checklist

- [x] Added contributor object in ascending order in `contributors.json`
- [x] Github action build passing
- [x] No merge conflicts

### CODE REVIEW

**Comment by subeshb1** [comment]
There are conflicts

**Review by subeshb1 — CHANGES_REQUESTED** [review]
Fix syntax and order in ascending alphabetically

**Comment by mohsin-code** [comment]
Changes done! Please merge. Thank you.

**Comment by subeshb1** [comment]
Hi @mohsin-code. When you have done everything described in the issue and meet every checklist. The PR will be merge. Not a good practice to request the merging of PRs

**Review by subeshb1 — APPROVED** [review]

**Pull request merged**
