### PR TITLE
Added Contributor Info & Sorted Using Command

### PR DESCRIPTION
**Pull request by RuteshRathod**
## Issue

Join developer community stats / First PR (Open for everyone) #259
## Description

Updated Contributor.json with adding mu details and also used "npx sort-json contributors.json --ignore-case" command to sort the JSON
## Checklist

- [x] Added contributor object in ascending order in `contributors.json`
- [x] Github action build passing
- [x] No merge conflicts

### CODE REVIEW

**Review by subeshb1 — APPROVED** [review]

**Comment by RuteshRathod** [comment]
**_Thank you for creating such thing for beginners and thanks for accepting Pull Request._**

**Comment by RuteshRathod** [comment]
_Dear @subeshb1  can you please add the label of hacktoberfest and hacktoberfest-accepted as it would really helpful for me._

**Comment by subeshb1** [comment]
It is not necessary.  Your pr will be accepted in 14 days of pr submission

**Comment by RuteshRathod** [comment]
ok, thank you @subeshb1 sir.

**Pull request merged**
