### PR TITLE
Had to fix a comma I had forgotten in contributors.json

### PR DESCRIPTION
**Pull request by nyd3lig**
## Checklist

- [ ] Added contributor object in ascending order in `contributors.json`
- [ ] Github action build passing
- [ ] No merge conflicts

### CODE REVIEW

**Comment by nyd3lig** [comment]
Not sure what the fail is, could someone help me out?

**Comment by subeshb1** [comment]
It is because you haven't kept your information in ascending order in the list. We have to keep it in ascending order to avoid conflicts between PRs. For now, I'll fix it. Be sure to read the full description before taking an issue

**Comment by nyd3lig** [comment]
> It is because you haven't kept your information in ascending order in the list. We have to keep it in ascending order to avoid conflicts between PRs. For now, I'll fix it. Be sure to read the full description before taking an issue

I was sure it was in ascending order 🤔 or did I miss understand ascending? I'd love to fix it myself since I'm sure it'll help me learn

**Comment by subeshb1** [comment]
It's ok @nyd3lig here is another issue for you #121

**Comment by nyd3lig** [comment]
> It's ok @nyd3lig here is another issue for you #121

OOoooo, it meant ascending order as in alphabetically?!

**Pull request merged**
