### PR TITLE
Made Changes for Grammatical Typos in README.md 

### PR DESCRIPTION
**Pull request by RuteshRathod**
## Issue

https://github.com/subeshb1/developer-community-stats/issues/510#
## Description

Made changes for README.md with respect to grammatical typos.

## Checklist

- [x] Github action build passing
- [x] No merge conflicts

### CODE REVIEW

**Comment by RuteshRathod** [comment]
Created Pull Request on the basis of Issue: https://github.com/subeshb1/developer-community-stats/issues/510#

**Comment by subeshb1** [comment]
Let's extend this to the entire repository, not just a single file @RuteshRathod

**Comment by subeshb1** [comment]
Hi @RuteshRathod to avoid spams and not encourage other contributors to make unnecessary changes I'm closing this PR. 

This can be accepted after Hacktoberfest, but to avoid spam I'll be rejecting this. If you however can fix typos all across repos than I can make an exception

**Comment by RuteshRathod** [comment]
ok sir, No Problem

**Pull request closed without merging**
