### PR TITLE
Contributor-added

### PR DESCRIPTION
**Pull request by SrijitaSarkar99**

### CODE REVIEW

**Review by subeshb1 — APPROVED** [review]

**Comment by subeshb1** [comment]
It looks like there are conflicts can you fix them?

**Comment by subeshb1** [comment]
@SrijitaSarkar99 👆

**Comment by SrijitaSarkar99** [comment]
@subeshb1 
Sorry for late reply.
Thank you for approving and merging it.

Thanks and Regards,
Srijita

**Comment by subeshb1** [comment]
Its ok @SrijitaSarkar99. This is a place to learn. Here is another issue if you want to contribute: #121 

Don't forget to star, share the repository, and follow me.

**Pull request merged**
